#spring.application.name=lastmiledelivery

server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lastmiledelivery?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456789
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  messages:
    basename: i18n/messages
    encoding: UTF-8
    default-locale: en

api:
  prefix: api

jwt:
  expiration: 3600 # 1 gio
  refreshable-expiration: 864000 # 10 ngay
  secretKey: TaqlmGv1iEDMRiFp/pHuID1+T84IABfuA0xXh4GhiUI=

